"""add_driver_model

Revision ID: 6bee954fa155
Revises: 425992d849c6
Create Date: 2026-07-12 14:47:16.559934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bee954fa155'
down_revision: Union[str, Sequence[str], None] = '425992d849c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_category', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'OnTrip', 'OffDuty', 'Suspended', name='driver_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
